name: CI/CD Pipeline - Flask App

on:
  push:
    branches:
      - main
      - staging
  release:
    types: [created]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create and activate virtual environment, install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests in virtual environment
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          source venv/bin/activate
          pytest

  deploy-to-staging:
    needs: build-and-test
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_KEY }}
          port: 22
          script: |
            cd B10_Vaibhav_Assignment_06_CICD
            git pull origin staging
            export MONGO_URI=${{ secrets.MONGO_URI }}
            sudo systemctl restart b10flask.service

  deploy-to-production:
    needs: build-and-test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_KEY }}
          port: 22
          script: |
            cd B10_Vaibhav_Assignment_06_CICD
            git pull origin main
            export MONGO_URI=${{ secrets.MONGO_URI }}
            sudo systemctl restart b10flask-prod.service
